#!/usr/bin/env python3
"""Build `dist/` and `audit/` deterministically.

Policy:
- dist/ is the publishable distribution surface (copy of ontology sources + contexts + shapes)
- audit/ contains checksums + metadata for reproducibility

This repo keeps dist/ and audit/ as CI-generated by default.
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
AUDIT = ROOT / "audit"

INCLUDE_DIRS = ["Upper", "Middle", "Lower", "Domains", "Platform", "prophet", "epi", "catalog", "shapes", "contexts", "imports", "docs"]

def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def main() -> int:
    if DIST.exists():
        shutil.rmtree(DIST)
    if AUDIT.exists():
        shutil.rmtree(AUDIT)
    DIST.mkdir(parents=True, exist_ok=True)
    AUDIT.mkdir(parents=True, exist_ok=True)

    manifest = []
    for d in INCLUDE_DIRS:
        src = ROOT / d
        if not src.exists():
            continue
        for f in sorted(src.rglob("*")):
            if f.is_dir():
                continue
            rel = f.relative_to(ROOT)
            out = DIST / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, out)
            manifest.append({
                "path": str(rel).replace(os.sep, "/"),
                "sha256": sha256_file(f),
                "bytes": f.stat().st_size,
            })

    (AUDIT / "dist_manifest.json").write_text(json.dumps({
        "version": "0.1.0",
        "generated_utc": __import__("datetime").datetime.utcnow().isoformat() + "Z",
        "files": manifest,
    }, indent=2), encoding="utf-8")

    print(f"Built dist/ with {len(manifest)} files.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
