#!/usr/bin/env python3
"""Ingest upstream SourceOS draft GlossaryTerms → Platform/sourceos/glossary.ttl (spec-first).

The upstream vocab-currency loop (sourceos-spec `tools/vocab_currency_loop.py`) emits conformant
status:draft `GlossaryTerm` JSON — the currency-detection → proposal side of the lifecycle. This
generator is the ontogenesis on-ramp: it reads those JSON docs and emits ONE Turtle module (the
only form the SHACL gate ingests), mapping the srcos GlossaryTerm shape onto SKOS:

    name        -> skos:prefLabel
    definition  -> skos:definition
    status      -> srcos:glossaryStatus   (draft|approved|deprecated)
    id (urn)    -> srcos:sourceUrn         (provenance) + minted http subject IRI

Namespace reconciliation: the repo binds `srcos:` = https://schemas.srcos.ai/v2/, but upstream ids
are `urn:srcos:glossary:<slug>` URNs. We mint an http subject IRI in the existing srcos namespace
(`.../v2/glossary/<slug>`) so the term links cleanly into the graph, and keep the original URN as
`srcos:sourceUrn`. Additive, spec-first: edit this generator (or the upstream loop), not the .ttl.

    python3 scripts/ingest_srcos_glossary.py                       # from the seed dir
    python3 scripts/ingest_srcos_glossary.py --input <dir-of-json> # e.g. the loop's proposals
    python3 scripts/ingest_srcos_glossary.py --check               # fail if the .ttl is stale
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "examples" / "sourceos" / "glossary-seed"
OUT = ROOT / "Platform" / "sourceos" / "glossary.ttl"
SRCOS = "https://schemas.srcos.ai/v2/"

HEADER = f"""@base <https://socioprophet.github.io/ontogenesis/> .
@prefix srcos: <{SRCOS}> .
@prefix srcosg: <{SRCOS}glossary/> .
@prefix upper: <https://socioprophet.github.io/ontogenesis/upper#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dct: <http://purl.org/dc/terms/> .

##############################################################################
# SourceOS Glossary — the vocabulary substrate, lifted into Ontogenesis.
#
# GENERATED by scripts/ingest_srcos_glossary.py from upstream draft GlossaryTerm JSON
# (sourceos-spec tools/vocab_currency_loop.py -> result.proposedTerms). Additive, spec-first.
# Edit the generator or the upstream loop, not this file.
##############################################################################

<Platform/sourceos/glossary.ttl> a owl:Ontology ;
  dct:title "SourceOS Glossary" ;
  dct:description "Vocabulary-as-governance-substrate: SourceOS/SociOS glossary terms lifted from the sourceos-spec GlossaryTerm contract via the governed vocab-currency loop. A term regulates state only once captured (label+definition) and approved." ;
  dct:source "sourceos-spec:tools/vocab_currency_loop.py" ;
  owl:versionInfo "0.1.0" ;
  owl:imports <Upper/upper-core.ttl>, <Platform/platform.ttl> .

### TBox — a SourceOS glossary term is a SKOS concept in the governed graph.
srcos:GlossaryTerm a owl:Class ;
  rdfs:subClassOf skos:Concept, upper:InformationArtifact ;
  rdfs:label "SourceOS glossary term" ;
  rdfs:comment "A term from the sourceos-spec GlossaryTerm contract; regulates estate state once captured and approved." .

srcos:glossaryStatus a owl:DatatypeProperty ;
  rdfs:domain srcos:GlossaryTerm ; rdfs:range xsd:string ;
  rdfs:label "glossary status" ; rdfs:comment "draft | approved | deprecated (mirrors GlossaryTerm.status)." .

srcos:sourceUrn a owl:DatatypeProperty ;
  rdfs:domain srcos:GlossaryTerm ; rdfs:range xsd:string ;
  rdfs:label "upstream URN" ; rdfs:comment "The urn:srcos:glossary: id this term was ingested from (provenance)." .

### ABox — generated term instances.
"""


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def load_terms(input_dir: Path) -> list[dict]:
    terms = {}
    for f in sorted(glob.glob(str(input_dir / "*.json"))):
        doc = json.loads(Path(f).read_text(encoding="utf-8"))
        if doc.get("type") != "GlossaryTerm" or not str(doc.get("id", "")).startswith("urn:srcos:glossary:"):
            continue
        terms[doc["id"]] = doc  # dedup by urn
    return list(terms.values())


def render(terms: list[dict]) -> str:
    out = [HEADER]
    for t in sorted(terms, key=lambda d: d["id"]):
        slug = t["id"].split(":")[-1]
        name = esc(t.get("name", slug))
        definition = esc(t.get("definition", ""))
        status = t.get("status", "draft")
        out.append(
            f"srcosg:{slug} a srcos:GlossaryTerm ;\n"
            f'  skos:prefLabel "{name}" ;\n'
            f'  skos:definition "{definition}" ;\n'
            f'  srcos:glossaryStatus "{status}" ;\n'
            f'  srcos:sourceUrn "{t["id"]}" .\n'
        )
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=str(SEED), help="directory of draft GlossaryTerm JSON")
    ap.add_argument("--check", action="store_true", help="fail if Platform/sourceos/glossary.ttl is out of date")
    args = ap.parse_args()

    terms = load_terms(Path(args.input))
    if not terms:
        print(f"no GlossaryTerm JSON found under {args.input}", file=sys.stderr)
        return 1
    ttl = render(terms)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.strip() != ttl.strip():
            print(f"STALE: {OUT} does not match `ingest_srcos_glossary.py --input {args.input}`; regenerate.",
                  file=sys.stderr)
            return 1
        print(f"OK: {OUT} is up to date ({len(terms)} terms)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(ttl, encoding="utf-8")
    print(f"wrote {OUT} ({len(terms)} terms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
