#!/usr/bin/env python3
"""Pre-commit hook: disallow direct staged edits under dist/ or audit/.

The authoritative policy is: dist/ and audit/ are generated by CI/build scripts.
"""
from __future__ import annotations

import subprocess
import sys

def main() -> int:
    try:
        out = subprocess.check_output(["git", "diff", "--name-only", "--cached"], text=True)
    except Exception:
        # If not in git context, do nothing.
        return 0
    bad = []
    for line in out.splitlines():
        if line.startswith("dist/") or line.startswith("audit/"):
            bad.append(line)
    if bad:
        print("Direct edits to dist/ or audit/ are not allowed:")
        for b in bad:
            print(" -", b)
        print("Run scripts/build_dist.py and scripts/ledger_build.py; let CI generate artifacts.")
        return 1
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
